version: '3.1'
services:
  db:
    image: mysql
    container_name: gestion-spring-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GESTION-SPRING